[package]
name = "ntp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }

log = "0.4"
env_logger = "0.9"
byteorder = "1.4"
bincode = "1.3.3"
